# syshmi-updater manifest
version       = "0.0.1a"
binary        = "syshmi-core"
checksum      = "0849865d679fbd4e050390a378f4e9f24946f5db0d5a46c60cc1233f1bb0a855" # sha256
start_command = "/srv/firmware/syshmi-core"
rollback_keep = 2

