# syshmi-updater manifest v0.1

download_url    = "https://github.com/user-attachments/files/24353073/syshmi-core-v0.0.1a.tar.gz"
version_set     = "0.0.1a"

[[modules]]
name            = "syshmi-core-v"
version         = "0.0.1-alpha"
checksum        = "0849865d679fbd4e050390a378f4e9f24946f5db0d5a46c60cc1233f1bb0a855" # sha256
target_dir      = "/srv/firmware/"
start_command   = "/srv/firmware/syshmi-core"
rollback_keep   = 2



